# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo $(PipelineLevelVariable)
    - bash: echo Build First Job
  - job: Job2
    steps:
    - bash: java --version
    - bash: node --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   jobs:
#   - job: Job1
#     steps:
#     - bash: echo $(environment)Deploy First Job
#   - job: Job2
#     steps:
#     - bash: echo DevDeploy Second Job

# - stage: QADeploy
#   variables:
#     environment: QA
#   jobs:
#   - job: Job1
#     steps:
#     - bash: echo $(environment)Deploy First Job
#   - job: Job2
#     steps:
#     - bash: echo QADeploy Second Job

# - stage: ProdDeploy
#   jobs:
#   - job: Job1
#     steps:
#     - bash: echo ProdDeploy First Job
#   - job: Job2
#     steps:
#     - bash: echo ProdDeploy Second Job

